### ISSUE TITLE
Support default x-amazon-apigateway-integration

### ISSUE THREAD

**Issue by henhal** [yndlingsfar/serverless-openapi-integration-helper#18]
One annoying thing about the API gateway OpenAPI extensions is that there's no way to supply a default `x-amazon-apigateway-integration` object, so it has to be repeated for each and every operation even though quite often it will be exactly identical for every operation, e.g.:

```
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: arn:aws:apigateway:eu-west-1:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:<account-id>:function:<function>/invocations
```

Would it make sense to add support to this plugin for populating a default `x-amazon-apigateway-integration` object into each operation? It would make it much simpler to deal with large APIs where each integration is the same.
